package com.ek.ws.spring.sei;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2018-02-01T03:06:37.231+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "OrderImplService", 
                  wsdlLocation = "file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/ws-client-cxf/src/main/java/springws.wsdl",
                  targetNamespace = "http://sei.spring.ws.ek.com/") 
public class OrderImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sei.spring.ws.ek.com/", "OrderImplService");
    public final static QName OrderImplPort = new QName("http://sei.spring.ws.ek.com/", "OrderImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/ws-client-cxf/src/main/java/springws.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/ws-client-cxf/src/main/java/springws.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OrderImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IOrder
     */
    @WebEndpoint(name = "OrderImplPort")
    public IOrder getOrderImplPort() {
        return super.getPort(OrderImplPort, IOrder.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IOrder
     */
    @WebEndpoint(name = "OrderImplPort")
    public IOrder getOrderImplPort(WebServiceFeature... features) {
        return super.getPort(OrderImplPort, IOrder.class, features);
    }

}
