package com.ek.ws.interceptor.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2018-01-30T03:46:09.107+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://sei.interceptor.ws.ek.com/", name = "ITestInterceptor")
@XmlSeeAlso({ObjectFactory.class})
public interface ITestInterceptor {

    @WebMethod
    @RequestWrapper(localName = "getMyInfo", targetNamespace = "http://sei.interceptor.ws.ek.com/", className = "com.ek.ws.interceptor.sei.GetMyInfo")
    @ResponseWrapper(localName = "getMyInfoResponse", targetNamespace = "http://sei.interceptor.ws.ek.com/", className = "com.ek.ws.interceptor.sei.GetMyInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getMyInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
