package com.ek.ws.hello.sei;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2018-01-30T02:36:58.139+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "HelloWSImplService", 
                  wsdlLocation = "file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/cxf-client/src/main/java/hellows.wsdl",
                  targetNamespace = "http://sei.hello.ws.ek.com/") 
public class HelloWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sei.hello.ws.ek.com/", "HelloWSImplService");
    public final static QName HelloWSImplPort = new QName("http://sei.hello.ws.ek.com/", "HelloWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/cxf-client/src/main/java/hellows.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/cxf-client/src/main/java/hellows.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IHelloWS
     */
    @WebEndpoint(name = "HelloWSImplPort")
    public IHelloWS getHelloWSImplPort() {
        return super.getPort(HelloWSImplPort, IHelloWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloWS
     */
    @WebEndpoint(name = "HelloWSImplPort")
    public IHelloWS getHelloWSImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWSImplPort, IHelloWS.class, features);
    }

}
