package com.ek.ws.interceptor.checkuser.sei;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2018-01-31T02:34:45.327+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "CheckUserInterceptorImplService", 
                  wsdlLocation = "file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/cxf-client/src/main/java/checkUserInterceptorws.wsdl",
                  targetNamespace = "http://sei.checkuser.interceptor.ws.ek.com/") 
public class CheckUserInterceptorImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sei.checkuser.interceptor.ws.ek.com/", "CheckUserInterceptorImplService");
    public final static QName CheckUserInterceptorImplPort = new QName("http://sei.checkuser.interceptor.ws.ek.com/", "CheckUserInterceptorImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/cxf-client/src/main/java/checkUserInterceptorws.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CheckUserInterceptorImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/Workspace/eclipse/workspace4.5/demo_webservice/cxf-client/src/main/java/checkUserInterceptorws.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CheckUserInterceptorImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CheckUserInterceptorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckUserInterceptorImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CheckUserInterceptorImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CheckUserInterceptorImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CheckUserInterceptorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ICheckUserInterceptor
     */
    @WebEndpoint(name = "CheckUserInterceptorImplPort")
    public ICheckUserInterceptor getCheckUserInterceptorImplPort() {
        return super.getPort(CheckUserInterceptorImplPort, ICheckUserInterceptor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICheckUserInterceptor
     */
    @WebEndpoint(name = "CheckUserInterceptorImplPort")
    public ICheckUserInterceptor getCheckUserInterceptorImplPort(WebServiceFeature... features) {
        return super.getPort(CheckUserInterceptorImplPort, ICheckUserInterceptor.class, features);
    }

}
