package com.ek.ws.interceptor.checkuser.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2018-01-31T02:34:45.288+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://sei.checkuser.interceptor.ws.ek.com/", name = "ICheckUserInterceptor")
@XmlSeeAlso({ObjectFactory.class})
public interface ICheckUserInterceptor {

    @WebMethod
    @RequestWrapper(localName = "checkUser", targetNamespace = "http://sei.checkuser.interceptor.ws.ek.com/", className = "com.ek.ws.interceptor.checkuser.sei.CheckUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://sei.checkuser.interceptor.ws.ek.com/", className = "com.ek.ws.interceptor.checkuser.sei.CheckUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.ek.ws.interceptor.checkuser.sei.UserBean arg0
    );
}
