package com.ek.ws.hello.sei;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2018-02-01T02:12:44.855+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://sei.hello.ws.ek.com/", name = "IHelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloWS {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://sei.hello.ws.ek.com/", className = "com.ek.ws.hello.sei.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://sei.hello.ws.ek.com/", className = "com.ek.ws.hello.sei.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
